### ISSUE TITLE
Add Yandex

### ISSUE THREAD

**Issue by cmfc31** [Nachtalb/reverse_image_search_bot#15]
Add Yandex option to search results instead of Bing.

**Comment by Nachtalb** [comment]
Or let bing be bing and add Yandex as an additional service, without removing bing. As stupid as it sounds, there was already an image which I only found via bing and not the others. The more the merrier.

**Comment by cmfc31** [comment]
Yeah, that's better. I noticed that sometimes reverse searches returns more or less results depending from your location.

**Comment by Nachtalb** [comment]
Done https://github.com/Nachtalb/reverse_image_search_bot/commit/ae71d792831507c16bd64ed9bdcf6963a3e932a2
